import { CreateImage } from "./utils.js";
export let sharedData = {
  canvas: document.querySelector("canvas"),
  keysAccess: false,
  isPaused: false,
  scoreBoard: 140,
  playerPowerUp: false,
  lastKey: "right",
};

export let keys = {
  left: {
    pressed: false,
  },
  right: {
    pressed: false,
  },
  space: {
    pressed: false,
  },
};

export const playerSprite = {
  stand: {
    cropXr: 250,
    cropXl: 130,
    cropY: 40,
    right: [
      CreateImage("/assets/images/player/right/Idle (1).png"),
      CreateImage("/assets/images/player/right/Idle (2).png"),
      CreateImage("/assets/images/player/right/Idle (3).png"),
      CreateImage("/assets/images/player/right/Idle (4).png"),
      CreateImage("/assets/images/player/right/Idle (5).png"),
      CreateImage("/assets/images/player/right/Idle (6).png"),
      CreateImage("/assets/images/player/right/Idle (7).png"),
      CreateImage("/assets/images/player/right/Idle (8).png"),
      CreateImage("/assets/images/player/right/Idle (9).png"),
      CreateImage("/assets/images/player/right/Idle (10).png"),
    ],
    left: [
      CreateImage("/assets/images/player/left/Idle (1).png"),
      CreateImage("/assets/images/player/left/Idle (2).png"),
      CreateImage("/assets/images/player/left/Idle (3).png"),
      CreateImage("/assets/images/player/left/Idle (4).png"),
      CreateImage("/assets/images/player/left/Idle (5).png"),
      CreateImage("/assets/images/player/left/Idle (6).png"),
      CreateImage("/assets/images/player/left/Idle (7).png"),
      CreateImage("/assets/images/player/left/Idle (8).png"),
      CreateImage("/assets/images/player/left/Idle (9).png"),
      CreateImage("/assets/images/player/left/Idle (10).png"),
    ],
    rightP: [
      CreateImage("/assets/images/player/right/IdleP (1).png"),
      CreateImage("/assets/images/player/right/IdleP (2).png"),
      CreateImage("/assets/images/player/right/IdleP (3).png"),
      CreateImage("/assets/images/player/right/IdleP (4).png"),
      CreateImage("/assets/images/player/right/IdleP (5).png"),
      CreateImage("/assets/images/player/right/IdleP (6).png"),
      CreateImage("/assets/images/player/right/IdleP (7).png"),
      CreateImage("/assets/images/player/right/IdleP (8).png"),
      CreateImage("/assets/images/player/right/IdleP (9).png"),
      CreateImage("/assets/images/player/right/IdleP (10).png"),
    ],
    leftP: [
      CreateImage("/assets/images/player/left/IdleP (1).png"),
      CreateImage("/assets/images/player/left/IdleP (2).png"),
      CreateImage("/assets/images/player/left/IdleP (3).png"),
      CreateImage("/assets/images/player/left/IdleP (4).png"),
      CreateImage("/assets/images/player/left/IdleP (5).png"),
      CreateImage("/assets/images/player/left/IdleP (6).png"),
      CreateImage("/assets/images/player/left/IdleP (7).png"),
      CreateImage("/assets/images/player/left/IdleP (8).png"),
      CreateImage("/assets/images/player/left/IdleP (9).png"),
      CreateImage("/assets/images/player/left/IdleP (10).png"),
    ],
  },
  run: {
    cropXr: 240,
    cropXl: 140,
    cropY: 30,
    right: [
      CreateImage("/assets/images/player/right/Run (1).png"),
      CreateImage("/assets/images/player/right/Run (2).png"),
      CreateImage("/assets/images/player/right/Run (3).png"),
      CreateImage("/assets/images/player/right/Run (4).png"),
      CreateImage("/assets/images/player/right/Run (5).png"),
      CreateImage("/assets/images/player/right/Run (6).png"),
      CreateImage("/assets/images/player/right/Run (7).png"),
      CreateImage("/assets/images/player/right/Run (8).png"),
    ],
    left: [
      CreateImage("/assets/images/player/left/Run (1).png"),
      CreateImage("/assets/images/player/left/Run (2).png"),
      CreateImage("/assets/images/player/left/Run (3).png"),
      CreateImage("/assets/images/player/left/Run (4).png"),
      CreateImage("/assets/images/player/left/Run (5).png"),
      CreateImage("/assets/images/player/left/Run (6).png"),
      CreateImage("/assets/images/player/left/Run (7).png"),
      CreateImage("/assets/images/player/left/Run (8).png"),
    ],
    rightP: [
      CreateImage("/assets/images/player/right/RunP (1).png"),
      CreateImage("/assets/images/player/right/RunP (2).png"),
      CreateImage("/assets/images/player/right/RunP (3).png"),
      CreateImage("/assets/images/player/right/RunP (4).png"),
      CreateImage("/assets/images/player/right/RunP (5).png"),
      CreateImage("/assets/images/player/right/RunP (6).png"),
      CreateImage("/assets/images/player/right/RunP (7).png"),
      CreateImage("/assets/images/player/right/RunP (8).png"),
    ],
    leftP: [
      CreateImage("/assets/images/player/left/RunP (1).png"),
      CreateImage("/assets/images/player/left/RunP (2).png"),
      CreateImage("/assets/images/player/left/RunP (3).png"),
      CreateImage("/assets/images/player/left/RunP (4).png"),
      CreateImage("/assets/images/player/left/RunP (5).png"),
      CreateImage("/assets/images/player/left/RunP (6).png"),
      CreateImage("/assets/images/player/left/RunP (7).png"),
      CreateImage("/assets/images/player/left/RunP (8).png"),
    ],
  },
};
